project:
  type: website
  resources: assets

website:
  title: "Bjørn's Site"
  site-url: https://bjorns.site
  back-to-top-navigation: true
  page-footer:
    left: "Powered by Quarto and Netlify"
    center:  "Redundant 2024, Bjørn Peare Bartholdy"
    right: 
      - icon: github
        href: https://github.com/bbartholdy/bjorns.website
        aria-label: GitHub
      - icon: mastodon
        href: https://fediscience.org/@bjorn
        aria-label: Mastodon
  sidebar:
    search: false
    style: floating
    tools: 
      - icon: github
        href: https://github.com/bbartholdy/
        aria-label: GitHub
      - icon: mastodon
        href: https://fediscience.org/@bjorn
        aria-label: Mastodon
    contents:
      - text: projects
        url: index.html#projects-section
      - text: publications
        url: index.html#publications-section
      - text: education
        url: index.html#education-section

format:
  html:
    theme:
      dark: [dark.scss]
      light: [not-dark.scss]
    css: styles.css
    bibliography: publications.bib
    csl: apa-chron.csl # modified version of APA style that orders articles chronologically
